name: Package release on tag push

on:
  push:
    tags: 'v*'

jobs:
  package_pro:
    name: Release Pro version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create ZIP archive
        run: |
          rm -rf ./templates/next-block-editor-app/src/extensions/Ai/AiFree.ts
          rm -rf ./templates/next-block-editor-app/src/extensions/AiImage/AiImageFree.ts
          rm -rf ./templates/next-block-editor-app/src/extensions/AiWriter/AiWriterFree.ts
          cd ./templates/next-block-editor-app && zip -r ../../blockeditor-template-pro.zip ./
      - name: Create Pro release on GitHub
        uses: softprops/action-gh-release@v2
        with:
          name: blockeditor-${{ github.ref_name }}
          generate_release_notes: true
          make_latest: true
          files: blockeditor-template-pro.zip
  package_basic:
    name: Release Basic version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install jq
        run: sudo apt update && sudo apt install jq
      - name: Create ZIP archive
        run: |
          bash ./convert-to-free-version.sh
          rm -rf ./templates/next-block-editor-app/src/extensions/Ai/AiFree.ts
          rm -rf ./templates/next-block-editor-app/src/extensions/AiImage/AiImageFree.ts
          rm -rf ./templates/next-block-editor-app/src/extensions/AiWriter/AiWriterFree.ts
          cd ./templates/next-block-editor-app && zip -r ../../blockeditor-template-basic.zip ./
      - name: Create Basic release on GitHub
        uses: softprops/action-gh-release@v2
        with:
          name: blockeditor-${{ github.ref_name }}
          generate_release_notes: true
          make_latest: false
          files: blockeditor-template-basic.zip
