name: Package release on tag push

on:
  push:
    tags: 'v*'

jobs:
  package_pro:
    name: Release Pro version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Copy files to temporary directory
        run: |
          mkdir -p /tmp/package
          cp -r . /tmp/package
      - name: Remove unnecessary files and directories
        run: |
          rm convert-to-free-version.sh
          rm -rf .github
          rm -rf .vscode
          rm -rf .git
          rm -rf templates/next-block-editor-app/extensions/Ai/AiFree.ts
          rm -rf templates/next-block-editor-app/extensions/AiImage/AiImageFree.ts
          rm -rf templates/next-block-editor-app/extensions/AiWriter/AiWriterFree.ts
      - name: Create ZIP archive
        run: |
          cd /tmp/package
          zip -r /tmp/template.zip
      - name: Create Pro release on GitHub
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}-pro
          generate_release_notes: true
          make_latest: true
          files: /tmp/template.zip
  package_basic:
    name: Release Basic version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Copy files to temporary directory
        run: |
          mkdir -p /tmp/package
          cp -r . /tmp/package
      - name: Convert to free version
        run: |
          bash /tmp/package/convert-to-free-version.sh
      - name: Remove unnecessary files and directories
        run: |
          rm convert-to-free-version.sh
          rm -rf .github
          rm -rf .vscode
          rm -rf .git
          rm -rf templates/next-block-editor-app/extensions/Ai/AiFree.ts
          rm -rf templates/next-block-editor-app/extensions/AiImage/AiImageFree.ts
          rm -rf templates/next-block-editor-app/extensions/AiWriter/AiWriterFree.ts
      - name: Create ZIP archive
        run: |
          cd /tmp/package
          zip -r /tmp/template.zip
      - name: Create Pro release on GitHub
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}-basic
          generate_release_notes: true
          make_latest: false
          files: /tmp/template.zip
